import Box from "@/components/faq/Box";

const FAQs = [
  {
    id: 1,
    question: "How can I create a discussion topic on TeachCorner?",
    answer:
      "It’s simple! Just click on the ‘Create Topic’ button, enter your question or topic in the field provided, and submit it. Your topic will then be available for the entire TeachCorner community to view and discuss.",
  },
  {
    id: 2,
    question: "What kind of topics can I discuss on TeachCorner?",
    answer:
      "You can discuss a wide range of topics related to programming, from specific coding problems to broader concepts in software development. Whether you’re a beginner asking about basic syntax or an experienced developer seeking best practices, all programming-related discussions are welcome.",
  },
  {
    id: 3,
    question: "Can I respond to topics created by other users?",
    answer:
      " Absolutely! TeachCorner is all about community learning. Feel free to contribute to any discussion by providing answers, sharing resources, or even asking follow-up questions.",
  },
  {
    id: 4,
    question:
      "Are there any guidelines for creating or participating in discussions?",
    answer:
      "Yes, we encourage respectful and constructive conversations. Make sure your topics and responses are clear and relevant to programming. Avoid off-topic discussions and adhere to our community guidelines to maintain a positive learning atmosphere.",
  },
  {
    id: 5,
    question: "How do I find topics that interest me?",
    answer:
      "You can use the search function to find topics by keywords, or you can browse through categories that match your interests. We also have a tagging system that helps you quickly find discussions on specific programming languages or concepts.",
  },
];
const FaqPage = () => {
  return (
    <main className="mt-20">
      <h1 className=" text-3xl font-bold text-center mt-6 tracking-wider">
        Frequently Asked Questions
      </h1>
      <p className=" text-center text-gray-700 text-sm font-medium tracking-wide mt-2 mb-6">
        Here are some of our FAQs generated by ai.
      </p>
      {FAQs.map((faq) => (
        <Box
          value={`item-${faq.id}`}
          key={faq.id}
          question={faq.question}
          answer={faq.answer}
        />
      ))}
    </main>
  );
};

export default FaqPage;
